var checkAuth = require('../middleware/checkAuth');

module.exports = function(app) {
    app.get('/', require('./frontpage').get);
    app.post('/getArticles', checkAuth, require('./frontpage').getArticles);
    app.post('/getArticle', checkAuth, require('./frontpage').getArticle);
    app.post('/edit_article/getArticle', checkAuth, require('./frontpage').getArticle);
    app.post('/deleteArticles', checkAuth, require('./frontpage').deleteArticles);
    app.post('/up_position', checkAuth, require('./frontpage').up_position);
    app.get('/login', require('./login').get);
    app.post('/logout', require('./logout').post);
    app.post('/login', require('./login').post);
    app.get('/reg', require('./reg').get);
    app.post('/reg', require('./reg').post);
    app.get('/pas', require('./pas').get);
    app.get('/manage_acc', checkAuth, require('./manage_acc').get);
    app.post('/checkAccount', checkAuth, require('./manage_acc').checkAccount);
    app.post('/addAccount', checkAuth, require('./manage_acc').addAccount);
    app.post('/getAccounts', checkAuth, require('./manage_acc').getAccounts);
    app.post('/getAccountsOnSite', checkAuth, require('./manage_acc').getAccountsOnSite);
    app.post('/sendAccountInfo', checkAuth, require('./manage_acc').sendAccountInfo);
    app.post('/deleteAccount', checkAuth, require('./manage_acc').deleteAccount);
    app.post('/getAccountInfo', checkAuth, require('./manage_acc').getAccountInfo);
    app.get('/add', checkAuth, require('./add').get);
    app.post('/add', checkAuth, require('./add').add);
    app.post('/add_from', checkAuth, require('./add').add_from);
    app.post('/getAllArticles', checkAuth, require('./add').getAllArticles);
    app.post('/getArticleAll', checkAuth, require('./add').getArticleAll);
    app.post('/pas', require('./pas').post);
    app.get('/changepw/:id', require('./changepw').get);
    app.post('/changepw/:id', require('./changepw').post);
    app.get('/activate/:id', require('./reg').activate);
    app.post('/testEmail', require('./check').testEmail);
    app.post('/checkCode', require('./check').checkCode);
    app.get('/edit_article/:id', checkAuth, require('./edit_article').get);
    app.post('/edit_article/saveArticle', checkAuth, require('./edit_article').saveArticle);
    app.post('/edit_article/addImage', checkAuth, require('./edit_article').addImage);
    app.post('/edit_article/delete', checkAuth, require('./edit_article').delete);
    app.post('/post_article', checkAuth, require('./manage_article').post_article);
    app.post('/delete_article', checkAuth, require('./manage_article').delete_article);
    app.post('/find_status', checkAuth, require('./manage_article').find_status);
    app.post('/activate_article', checkAuth, require('./manage_article').activate_article);
    app.post('/deactivate_article', checkAuth, require('./manage_article').deactivate_article);
    app.post('/up_position_one', checkAuth, require('./manage_article').up_position);
    app.get(/.*/,require('./error').get);
};
