post_p25 = "Log in completed"
post_p50 = "Category choosed"
post_p75 = "Information added"
post_p100 = "Personal information added"
del_p25 = "Log in completed"
del_p50 = "Firts search completed"
del_p75 = "Firts delete completed"
del_p100 = "Second delete completed"
stat_p25 = "Log in completed"
stat_p50 = "Search completed"
stat_p75 = "Processing status completed"
stat_p100 = "Return status"
activ_p25 = "Log in completed"
activ_p50 = "Search completed"
activ_p75 = "Activation processed"
activ_p100 = "Return response"
deactiv_p25 = "Log in completed"
deactiv_p50 = "Search completed"
deactiv_p75 = "Deactivation processed"
deactiv_p100 = "Return response"
def rander(url):
	return '<a target="_blank" href="' + url[-79:] + '">View report</a>'